- getGFSData.py
added functions for downloading gfs data
> Noah's Latest work

- misc-tools/tif_extracter.py
add misc-tools and a script to extract data from multiband raster at points
> point data from multiband rasters

- data/nwm_forecast.py
Modified Adil's NWM functions to address issues #5 and #15; `nwm_functions.get_data()` now has an option to save dataframes as CSV files, `nwm_forecast.GetForecastFile()` now implements the generic `lib.download_data()`, and directory structure for NWM downloads is cleaned up to match that of GFS downloads.
> **REBASE 1st** NWM Download Functions Cleanup

- data/nwm_forecast.py
- default_settings.json
- models/aem3d/AEM3D_prep_IAM.py
- models/aem3d/AEM3D_prep_worker.py
- models/aem3d/get_args.py
- models/aem3d/waterquality.py
- fixed the bug in `waterquality.py` that was causing phosphorus data to be lost in `flowdf` for JewettStevens- see line 252, 256, and 271
- added a boolean flag in the settings that determines which data directory structure to use. Default is the new data dir structure. Pass the flag `--old_dirs` to use the old structure
- fixed a couple of other minor bugs (variable name changes, args, etc) that were breaking the model
> Patch and Update Main for Production

- data/btv_met.py
Then... .json() to test for valid web API return value instead of previous test based on length
> Update btv_met to try... except

- data/gfs_tools.py
- data/nwm_forecast.py
- lib.py
Modified:
-  `lib.py/download_data()`
- `data/gfs_tools.py/download_gfs()`
- `data/nwm_forecast.py/GetForecastFile()`
- `data/nwm_forecast.py/download_forecast_files()`
to fix issue #40 
Also, I converted all of the indentation spaces to tabs (4 spaces = 1 tab) in each of these files, as vscode kept raising an issue that indentations did not match. Converting fixed this issue. If this change raises an issue for anyone else, please let me know and we can go back to spaces.
> Remove log parameter from download functions

- .gitignore
- examples/get_data_demo.ipynb
Created a Jupyter notebook under `examples/get_data_demo.ipynb` to showcase how to use our data grabbers. Also modified the `.gitignore` file to ignore `.log` files and `.ipynb_checkpoints/`
> add get_data_demo notebook

- batch/data/download_nwm_year.py
- batch/experiment_configTEMPLATE.json
- batch/launchExperiment.py
- batch/submitTEMPLATE.sh
- data/gfs_fc_thredds.py
- models/aem3d/AEM3D_prep_IAM.py
Mostly small bug fixes in this PR.
> Minor adjustments for 2019 scenarios

- lib.py
- models/aem3d/AEM3D_prep_IAM.py
Updates to make Missisquoi specific swr nudge and update stream flows to match scaling used in calibration.
> SWR Zone specific nudge and Flows at Calibration scaling

- .gitignore
- data/gfs_fc.py
- data/nwmretro_forcings_ob.py
- requirements.txt
Added a new file, `data/nwmretro_forcings_ob.py` adapted from Takis' script. Updated `requirements.txt.` to reflect new requirements for this get_data. Small unrelated changes:
- updated `.gitignore` to ignore all logs 
- uncommented an import line I noticed in `gfs_fc.py` that I commented out while working on the VACC a while ago.
> Create get_data() for NWM Retro Forcings

- data/cfs_fc.py
- data/utils.py
Finally pieced this module together. Also enhanced `data.utils.parse_to_datetime()` so that it can parse a `reference_date` string, which often includes hours.
> Add CFS Data Acquisition Module

- data/caflow_ob.py
Pretty simple change, as described in title above
> Change series returned by caflow_ob.get_data() from 'object' to 'float64'

- data/usgs_ob.py
Edits to `usgs_ob.py` so that when daily values are requested, data is returned with no time info added. IOW, timestamps are just dates, which is what is returned by the USGS API. This is how `caflow_ob.get_data()` functions as well. Instantaneous values still inherent time information from the API and are timestamps are accordingly UTC-localized
> usgs_ob.py: remove time/timezone info from being added to daily values

- data/lcd_ob.py
- data/utils.py
- models/aem3d/AEM3D_prep_IAM.py
The main goal of these commits were to:
1. Identify timeseries gaps in FEMC relative humidity data
2. Fill these gaps with data from the Burlington airport weather station (LCD dataset)
3. Integrate this gap-fill code into `AEM3D_prep_IAM.py`
Changes mainly occurred in:
- `lcd_oc.py`: enable `get_data()` to access and process relative humidity data
- `utils.py`: add new functions to identify temporal gaps in a pands.DatetimeIndex, plot multiple timeseries on the same figure
- `AEM3D_prep_IAM.py`: integrate FEMC gap-filling function, `femcRhumGapfill()` into the prep script. This function was added to `adjustFEMCLCD()`, so now the FEMC relhum series will regularly be checked for gaps.
> Workflow adjustments to address FEMC relative humidity gaps

- batch/experiment_configTEMPLATE.json
- batch/launchExperiment.py
- data/cfs_fc.py
- models/aem3d/AEM3D_prep_IAM.py
- models/aem3d/get_args.py
New changes in this branch:
- enable `cfs_fc.get_data()` to get surface pressure, add two methods to calculate relative humidity
- add CFS as a valid option for the forecast climatology dataset
- add new setting to `experiment_config.json` template to adjust length of forecast period, implement in `launchExperiment.py`
- adjust plots in `AEM3D_prep_IAM.py` to show data for longer forecast period
> Update CFS DA module and integrate into workflow (rebased with main)

- batch/submitTEMPLATE.sh
- data/lcd_ob.py
- default_settings.json
- models/aem3d/AEM3D_prep_IAM.py
- models/aem3d/Aem3dForcing.py
- models/aem3d/Aem3dForcings.py
- models/aem3d/get_args.py
- models/aem3d/waterquality.py
A fair bit of changes in this pull request. Most of them have been for the purpose of making the workflow more robust and functional for a greater variety of workflow parameters (for example, a multi-year model run, such as the one requested by Peter.) In that vein, I wrote up a new class to represent the various timeseries that we aggregate to force AEM3D. This class, called `Aem3dForcings.py`, is meant to be the link between our `data/` modules and all the prep work done in `AEM3D_prep_IAM.py`. While the class is only partially implemented right now, I'm envisioning that most of the data cleaning/preparation that is currently in the prep script will eventually be moved to the AEM3dForcings class. That way, the prep scrip becomes much more readable, and it will hopefully be easier to …
> New Aem3dForcings class partial implementation, tweaks and patches to launch 20-year Hindcast

- data/aorc_ob.py
zarr no longer supports using the s3fs S3Map for file access.  So, had to figure out another way to do it.  Fortunately, the Zarr documentation was helpful!
https://zarr.readthedocs.io/en/v3.0.0/user-guide/storage.html#remote-store
> Update filespec for Zarr

- batch/debug/debug_params.json
- batch/debug/feeDebug.py
- data/aorc_ob.py
- data/cfs_fc.py
- data/lcd_ob.py
- data/nwm_fc.py
- data/usgs_ob.py
- data/utils.py
- examples/get_data_demo.ipynb
A handful of our modules in `data/` were touched in this branch; here's a summary of major changes:
-  `lcd_ob.py`: rewrote this module to make one API call per station that includes every requested variable; previously the function made a separate call for each variable, which was unnecessarily inefficient and often would overwhelm the LCD server. Also tried to refactor some of the data-processing code to make it more modular and general where possible.
- `cfs_fc.py`: refactored this module to get data from either the NCEI THREDDS NetCDF subset service (ncss) or from their file server. Made independent download functions for both sources as well so users can just download the files they want en mass without having to process all of the data, which can add significant runtime when …
> Enhancements to Data Modules and Utilities

- models/aem3d/AEM3DInputFile.py
Adding in the new AEM3DInputFile class
> AEM3DInputFile: Adding AEM3DInputFile class

- data/cfs_fc.py
- data/nwm_fc.py
- data/tests/test_nwm_fc.py
- data/utils.py
Some big improvements to the NWM DA module in this one, including:
- Separate `download_nwm()` and `process_nwm()` methods that can be used independently of one another or `get_data()`
- `download_nwm()` now checks the source directly (google cloud services, NOMADS) to query what data from the requested forecast product are actually available to download
- `locations` and `variables` can now be of either type *dict* or *list*. If a dict is passed, then the locations/variables in the dataset will be renamed according to the dictionary; no renaming happens if just a list is passed
- added optional `reference_date` and `end_date_exclusive` parameters (in concordance with `cfs_fc.py`)
- `get_data()` calculates what timesteps to actually download from the forecast product based on …
> Rewrite NWM Data Acquisition module

- batch/debug/feeDebug.py
- data/nwm_fc.py
- models/aem3d/AEM3D_prep_IAM.py
Pretty much what the title says - this only changed a couple lines to AEM3D_prep_IAM.  Other minor tag-along changes include:
- Added code to feeDebug so that the program could identify and report out AEM3D_prep_IAM errors caused by bad NetCDF files (must commonly caused by bad or incomplete file downloads)
- Used vscode's GitHub copilot feature to add type hinting to the function signatures in nwm_fc.py and proofread documentation.
> Updating nwm_fc.get_data() calls in AEM3D_prep_IAM

- data/nwm_forcings_fc.py
- data/utils.py
New DA Module for getting NWM forcings data from the [NWM  Google Cloud Bucket](https://console.cloud.google.com/storage/browser/national-water-model). Can download and process the following forcing data directories found for any given date in the bucket:
- forcing_analysis_assim
- forcing_analysis_assim_extend
- forcing_medium_range
- forcing_short_range
Downloads entire NetCDF files, but only for the timespan requested. Processing function uses [xarray.open_mfdataset](https://docs.xarray.dev/en/stable/generated/xarray.open_mfdataset.html#id4) to load data, and can slice dataset by spatial extent and desired variables.
Note that the forcings dataset has it's own unique CRS, which is accessible in the xarray dataset.
> Create NWM Forcings Data Acquisition Module

- models/aem3d/AEM3DSheet.py
Wrote vectorized interpolate, `interpolate_stack()` method based on Scott's original `interpolate()` method. New vectorized method will take a multilayered  xarray DataArray or Dataset representing a timeseries of AEM3D sheets and quickly interpolate each spatial grid in the series. Plus, xarray meta data are preserved in this method.
> Add interpolate method for multilayered data array
