CIROH-UVM/forecast-workflow

data/nwm_forecast.py
Must've missed this bug in my last pull request... nonetheless all things nwm should work now.
=> fix curl import bug in nwm_forecast.py (ln 9)

data/gfs_tools.py, data/nwm_forecast.py, lib.py
Fix for issue #14 
Added new functions to `data/gfs_tools.py` and `data/nwm_forecast.py`:
- `download_gfs_threaded()`
- `download_nwm_threaded()`
These new functions directly call `lib.py/multithreaded_download()`, which by default uses 8 worker threads (half of the CPUs on the VM). `multithreaded_download()` maps the `lib.py/download_data()` function to a `ThreadPoolExecutor` to speed up downloads. For more details on the mechanics of the executor, see the [ThreadPoolExecutor docs](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor).
To implement, simply replace `download_gfs()`/`download_nwm()` with the new threaded versions of those functions.
=> Implement Multithreading in GFS/NWM Downloads

data/gfs_tools.py, data/nwm_forecast.py, lib.py
Created a new function, `mulithreaded_loading()` to `lib.py` to load data with multithreading. This function was implemented in:
- `gfs_tools.py/aggregate_station_df_dict()` - loading for GFS data was already pretty quick without multithreading, but added anyway for consistency
- `nwm_forecast.py/get_data()` - loading for NWM data now takes about 20 seconds
Resolves issue #39
=> Add multithreading to loading functions for GFS and NWM

data/gfs_tools.py, lib.py, models/aem3d/get_args.py
There are two major changes in this pull that address issue #12 :
1.  Updated `lib/get_calling_package()` so that it will return the package name of the original caller in the stack, as intended
2.  Added a class `lib/StreamToLogger` that when implemented, will forward all messages detined for the standard output (such as `print` statements) to the logger.
- **Note**: `print` statements will not print to cosole _and_ the logger, but are now recorded in _just_ the logger. Since our logging setup has a `StreamHandler` as well, these messages do ultimately end up in the console, just as log messages rather than plain print statements
=> Logging Paradigm Revamp

data/nwm_fc.py, habsForecast.py, lib.py, models/aem3d/AEM3D_prep_IAM.py, requirements.txt
Added a `requirements.txt` doc to the repo. Now, once a virtual environment is created, a user can install all dependencies with `pip install -r requirements.txt`. Also extended the capability of `nwm_fc.get_data()` so that it can get archived data (i.e. any data that does not follow the file system that NOMADS currently uses) from google buckets. The function can now also get other forecast ranges as well, such as `"short_range"`, `"long_range_mem3"`, etc.
=> Add Requirements and Google Bucket Archive Data Access

data/femc_ob.py, data/gfs_fc.py, data/gfs_fc_thredds.py, data/lcd_ob.py, data/nwm_fc.py, data/usgs_ob.py, default_settings.json, examples/get_data_demo.ipynb, lib.py, models/aem3d/AEM3D_prep_IAM.py, models/aem3d/AEM3D_prep_worker.py, models/aem3d/AEM3D_worker.py, models/aem3d/get_args.py, requirements.txt
A big update here; some of the major changes to note:
- Implemented Scott's Colchester Reef AirTemp adjustment for Missisquoi Bay
- New `get_data()` for grabbing archived GFS data from the [THREDDS](https://rda.ucar.edu/datasets/ds084.1/#) server in `gfs_fc_thredds.py`
- Changes to every `get_data()`:
-  Data grabbers are now start_date inclusive, end_date exclusive
-  Datetimes passed to data grabbers are assumed to be in UTC time, and return timeseries in UTC time
- Added a plotting mechanism to compare streamflow and weather data before and after forecast_start in `AEM3D_prep_IAM.py`
- Right now a global figure object is created and subplots are added in various functions as data is processed
- Should move towards an object-oriented approach to plotting in the future
=> Update in Preparation for HABs Hindcast Experiment

data/aorc_obs.py, data/nwmretro_forcings_ob.py
PR to close #63. Create a new file `aorc_obs.py` that contains a `get_data()` function to access data from the AORC  Amazon Web bucket. Also included a helper function to smash a dictionary of dataframes into a single dataframe that includes latitude and longitude. A couple differences from previous `get_data()`'s to note:
- There are two valid `return_type` arguments, 'series' and 'dataframe'
- 'series' will return the nested dictionary of pandas series, just as before
- 'dataframe' will return a single-layer dictionary, where the keys are location names and values are timeseries dataframes for those locations
I decided to change the default `return_type` argument to 'series' rather than 'dict' because both return types directly return a dictionary, which I think is a good starting point …
=> Create AORC Data Acquisition Module

data/aorc_ob.py, data/caflow_ob.py, data/femc_ob.py, data/gfs_fc.py, data/gfs_fc_thredds.py, data/lcd_ob.py, data/nwm_fc.py, data/nwmretro_forcings3_ob.py, data/nwmretro_forcings_ob.py, data/usgs_ob.py, data/utils.py
See commit messages for specific details, but overall:
- Add depreciation warning to `gfs_fc.py`
- Add `HourlyDryBulbTemperature` as a valid variable for `lcd_ob.get_data()`
- Replace all log to print statements for all modules
- Get rid of `return_type` parameter from all modules
- Add new utility functions
- Implement units for `aorc_ob.get_data()`. This is the ideal implementation of units for now: units are inferred from the raw dataset, and are added to the final nested dictionary. Units are included as columns when nested series dict is converted to dataframe via `utils.smash_to_dataframe()`
=> get_data Updates

batch/experiment_configTEMPLATE.json, batch/launchExperiment.py, batch/launchScenarioTEMPLATE.sh, batch/submitTEMPLATE.sh, data/utils.py, default_settings.json, models/aem3d/AEM3D_prep_IAM.py, models/aem3d/get_args.py
Changes to note:
- Franklin airport cloud data is now supplemented with BTV cloud data when there are large gaps in the Franklin timeseries
- workflow no longer has `root_dir` arg; instead there's a `data_dir` to specify where `prep_IAM` should look for/download data (GFS, NWM). Now you can run `forecast-workflow` from any dir you wish;
- fixed CFL bug - added `writefile()` call for lake level
- added lake level plot to `weatherVars.png`
=> Bug fixes and other updates to prepare for FEEv2

models/aem3d/AEM3D_prep_IAM.py
Pretty self-explanatory fix - not very elegant, but it works. If the `lcd.get_data()` fails due to franklin airport returning an empty json for the 7-day forecast period, then we will use the data from BTV instead.
=> add try/except clause to FSO cloud data grab for forecast period

data/usgs_ob.py
Update to `usgs_ob.py` to enable `get_data()` to access USGS Daily Values service via a new parameter, `serv`. By default, `usgs_ob.get_data()` accesses the Instantaneous Values service.
=> Access USGS daily values service

data/caflow_ob.py, models/aem3d/AEM3D_prep_IAM.py, models/aem3d/waterquality.py, models/islesRF/cqrf.py
What started as a small bug-squashing branch ended up being a significant change to our streamflow processing `AEM3D_prep_IAM.py` ... go figure!
In this pull request:
- Change default name for streamflow series or dataframe column to include units (default name is `'streamflow (m³/s)'`)
- Correct the `forecastStartIter` calculations so that it does not unnecessarily subtract an extra day from the forecast start date
- Create new function, `backfillCaFlowsSpinup()`, to fill in instantaneous streamflow (iv) gaps with daily values (dv) for Canadian gauges (rock and pike). This function applies to the _spinup period only_*. 
- Create new function, `getdailyflows()`, similar in structure to `getflowfiles()`, that gets dv streamflow from CA and USGS gauges to provide data for CQ calculations in …
=> Revamp streamflow pre-processing for AEM3D

models/aem3d/AEM3D_prep_IAM.py
Previously this function only merged IV streamflow series with daily values IF the first date in the IV series came after the spinup date. Now, the function looks at every IV series and fills in any missing dates with daily values.
Other changes to note:
- Time zone adjustment: IV data, by the time it reaches this function, is in UTC time. Daily values have no time info, but the assumption is that the date lines are constructed in the local timezone of the gauge, ET. So, in order to have a valid date comparison, the IV indices are converted back into ET before the indices of each series are compared. Then, after the comparison is done, daily values are set to 12:00 ET, then converted to UTC. Note that the IV data is not explicitly set back to UTC in the code, but this is because the IV …
=> Edits to backfillCaFlowsSpinup()

batch/debug/feeDebug.py, batch/launchExperiment.py, batch/launchScenarioTEMPLATE.sh, batch/submitTEMPLATE.sh, data/usgs_ob.py, models/aem3d/AEM3D.py, models/aem3d/AEM3D_prep_IAM.py, models/aem3d/AEM3D_prep_worker.py, models/aem3d/get_args.py
An assortment of tweaks and changes to get the workflow to run correctly for version 3. Also created a new debug script. Changes include:
- improve interoperability of `batch/` scripts; now, the only file you need to copy/paste into the FEE dir (`FEE_v3/`, etc) is launchScenarioTEMPLATE.sh.
- tweak `theBay.LastDate` and `iterations` so that AEM3D produces an even 7 days worth of timestamps
- have usgs_ob.py infer units from USGS API call
- create a new debug script to assess a FEE suite of runs for fatal errors, and report the cause of said error
=> Fixes for FEE_v3

data/femc_ob.py, data/utils.py, models/aem3d/AEM3D_prep_IAM.py
This PR rewrites the `femc_ob.py` module to access the correct FEMC dataset depending on the dates requested. Data prior to 7-26-2024 are acquired from the older 'V1' Colchester Reef dataset, data for dates after that come from the 'V2' dataset. Also added unit information to the series' names returned by the module, and tweaked the prep script to reflect these new names. Lastly, added some handy plotting functions to `utils.py` that can quickly and easily visualize a timeseries - great for quick visual inspection of data.
=> Rewriting FEMC DA Module

data/nwmv3_retro_fc.py, models/aem3d/AEM3D_prep_IAM.py
- new DA module, `nwmv3_retro_fc.py` to get streamflow (or other channel output) from the NWMv3.0 retrospective forecast on AWS
- integrate NWMv3.0 retrospective  into `AEM3D_prep_IAM.py` as a valid dataset for forecast hydrology
- `AEM3D_prep_IAM.py` refactor scaling of Missisquoi streamflow for Rock and Pike into separate function, `scaleRockandPikeQ()`
=> New DA module for NWMv3.0 retrospective forecast, integrate into workflow (rebased with main)

batch/debug/debug_params.json, batch/debug/feeDebug.py, batch/experiment_configTEMPLATE.json, batch/launchExperiment.py, batch/launchScenarioTEMPLATE.sh, default_settings.json
A few improvements I made since last time to make launching and debugging batches of runs a bit easier:
- Remove unnecessary harcoded directories that previously had to be manually edited 
- Add a start and end year command-line arg to `laucnhScenario.sh` that overrides whatever's in the `experiment_config` file
- Make the settings for the `feeDebug` script configurable, add an 'all' option to analyze all scenarios and years rather than having to write them all out in a list
=> Minor improvements to batch protocols

data/ci_data_download/config.json, data/ci_data_download/dataset.py, data/ci_data_download/download_ci_files.py
This Pull Request adds a Sentinel 3 CI Data Download module.
- `download_ci_files.py`: Handles downloading CI data.
- `dataset.py`: Processes and manages the downloaded data.
- `config.json`: Stores configuration settings.
The files are located in `data/ci_data_download/`.  
@pclemins Please review and let me know if any modifications are needed!
=> Added Sentinel 3 CI data download module in data/ci_data_download/

batch/debug/debug_params.json, batch/debug/feeDebug.py, batch/launchExperiment.py, data/utils.py
Integrating model cycle information (though the **hour field of the `forecast_start` parameter** in **configuration.json**. The `forecast_start` argument is passed along to the data getters in the prep_script, and the data getters infer the model cycle from the  passed start date. The `forecast_end` paramter _is also modified_ to include the model cycle hour, so that when the duration of the forecast simulation period is guaranteed to be calculated accurately (it is calculated as the number of days difference between forecast start and end). Model cycle information is also accordingly added to the debug scripts.
=> Ensure model cycle selection and alignment for Rakhshinda's additional hindcast scenarios

batch/experiment_configTEMPLATE.json, batch/launchExperiment.py, batch/launchScenarioTEMPLATE.sh, batch/submitTEMPLATE.sh
The changes in this branch arose because I wanted to create a stable production copy of repository that could be used to launch runs while I simultaneously work on new features in a development copy of the repository. So, I had to make sure that when I launch a suite of runs, the workflow knows which copy of the repository to use. So, I made a new setting, called `"forecast-workflow_path"` that specifies just that. I also adjusted `launchExperiment.py` so that it looks for `submitTEMPLATE.sh` relatively rather than at some hardcoded location.
Also included here: 
- change default `"data_dir"` to `/netfiles/ciroh/downloadedData/`
- cast `experiment_launch_params['forecast_days']` as a float rather than an int; this is handy for having more control over the length of the forecast period for …
=> Make the forecast-workflow repository path configurable

batch/debug/feeDebug.py, default_settings.json, models/aem3d/AEM3D_prep_IAM.py, models/aem3d/get_args.py
Rebased the 'peter' branch on top of the current main. This new branch, 'peter_rebased', now includes the following changes:
- Pat integrated some new forcing settings, `use_franklin_cloud_cover`, `use_btv_wind` and `generate_forcingdata_plots`
- - applied the `use_franklin_cloud_cover` to the forecast period in addition to the spinup period, which Pat implemented
- - 1 small syntax correction to Pat's changes
- fixing some broken logic I happened to notice in `feeDebug` (not necessary to launch Peter's run since it's the debug script, but still needs to be fixed nonetheless)
- - also modified `feeDebug` to delete run dirs that don't have an .out file, indicating they were never submitted. Deleting these run dirs is useful, because if the launch scripts (specifically …
=> Changes for Launching Peter's Long-term Hindcast v2

data/nwm_forcings_fc.py, examples/get_data_demo.ipynb
After some feedback from Mirce last week, I've made some changes to the NWM forcings module:
- `locations` parameter now accepts a `points` dictionary instead of a list. This allows users to label their coordinate pairs, and is consistent with other modules that allow for accepted named coordinate pairs to extract from gridded datasets
- Fixed an error caused by differing CRS coordinate names in some forcings datasets. 
- tweaked the end of `process_nwm_forcings` so that real grid coordinate values are still appended to the nested variables dictionary for each labeled point
- updated `get_data_demo.ipynb` to reflect the most recent versions of our data modules
=> Bug fixes for NWM forcings data module
